### ISSUE TITLE
CheckboxSelectionModel: click near checkbox interprets as common row click

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#122]
http://forums.ext.net/showthread.php?22956
Sencha bug thread (updated 2016-04-26): [click on checkbox selection cell behaves differently inside/outside check box](https://www.sencha.com/forum/showthread.php?285773)

Duplicates:
http://forums.ext.net/showthread.php?24100
http://forums.ext.net/showthread.php?27473
http://forums.ext.net/showthread.php?59984

**Update:** Sencha issue _EXTJS-8203_ allegedly fixed in ExtJS 4.2.0.489 release.
**Update by @DaniilVeriga**: not sure what they fixed, but the issue reported in the thread is still reproducible with ExtJS 6. A user has to click exactly a checkbox and not near.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8203_ allegedly fixed in ExtJS 4.2.0.489 release.

**Comment by fabriciomurta** [comment]
The original Sencha issue allegedly fixes this but seems it does not really fix it.
According to Daniil's update on the first:
_"not sure what they fixed, but the issue reported in the thread is still reproducible with ExtJS 6. A user has to click exactly a checkbox and not near."_
So we'll not consider this thread [http://www.sencha.com/forum/showthread.php?253527](http://www.sencha.com/forum/showthread.php?253527) as the one that determines whether this issue is fixed or not (a new bug report thread should be opened describing again the problem so we can get it fixed -- or the fix clarified).

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
This is indeed no longer reproducible in ExtJS 6.5.1 on example at http://examples.sencha.com/extjs/6.5.1/examples/classic/grid/grid-plugins.html
Clicking around the checkboxes, still within the check column's cell will not behave as a row click (deselecting all other selected rows).

The issue is also no longer reproducible in http://examples4.ext.net/#/GridPanel/Selection_Models/Checkbox_Selection/.
