### ISSUE TITLE
Component's UI property is not supported by Aria and Triton themes

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1245]
The following WebForms examples showcasing UI are directly affected by this issue:
    - Miscellaneous > UI > Button
    - Miscellaneous > UI > Panel
    - Miscellaneous > UI > Progress Bar
    - Miscellaneous > UI > Tab Panel
    - Miscellaneous > UI > Tip
    - Miscellaneous > UI > Window

By choosing either Triton (default) or Aria, the components with different `UI=` are not shown most of the time (if not at all times).

This has been identified when fixing #1217 items 117 to 122. It is not a side effect of the commit, as other themes works, but it was only possible to identify the issue after these items were fixed.

**Comment by fabriciomurta** [comment]
Forum thread complaining about this issue: [UI TabPanel](http://forums.ext.net/showthread.php?60834)

**Comment by DaniilVeriga** [comment]
Components' `UI="Primary|Success|Info|Danger|Warning"` styles have been added for the Triton theme. Supported in all browsers except IE8 and IE9.

As for Aria, UI is not going to be supported for this theme, since it is a very specific theme.

Components' `UI="Primary|Success|Info|Danger|Warning"` styles have been added for the Triton theme. Supported in all browsers except IE8 and IE9. It is already in the repo and will be released with 4.1.0.

As for Aria, UI is not going to be supported for this theme, since it is a very specific theme.
