### ISSUE TITLE
ComboBox does not include focusEnter nor focusLeave events

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1262]
Featured forum thread: [Lost Focus Listener and Input Mask](http://forums.ext.net/showthread.php?60637)

According to [Sencha documentation on combo box](http://docs.sencha.com/extjs/5.1/5.1.2-apidocs/#!/api/Ext.form.field.ComboBox-event-focusenter) there are the focusEnter and focusLeave events on combo box. These events are not wired in Ext.NET framework. A full review of the combo box revents and configs is advised.

These events have been introduced on 3.3 release.

**Comment by DaniilVeriga** [comment]
The events have been included to 4.0: #1128, #1229. So, I removed the 4.x label.

Please feel free to add to 3.x as well. 

By the way, I think the "Release 3.3" is not actual anymore since it was released. I will close the milestone and create a new "3.x" one that means the latest sources from GitHub (or SVN), because no public release is planned.

**Comment by fabriciomurta** [comment]
Fixed on svn revision **6749**.
