### ISSUE TITLE
syntax: ext-panel's Cls property does not accept a string argument

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1748]
The `ext-panel`'s `Cls` property tries to expand/evaluate text entered as if it were C# code or reference to variable names.

Reproduced at: [dataview/basic/overview/index.cshtml#L63](https://github.com/objectdotnet/ext7-sandbox/blob/e150ba6643b06b3ea028b38d81bdd14111a9e093/ExtNetCore7-20200325/Pages/examples/dataview/basic/overview/index.cshtml#L63)

This does not only conmpletely prevent the page frrom rendering, but also incurs into project build errors (syntax errors if the string is interpreted to non-existing resources).

**Comment by geoffreymcgill** [comment]
The `Cls` config in Ext JS can accept a `string` or a `string[]`. Because of a limitation within ASP.NET TagHelpers in setting strings, in order to support `string` types we needed to add a dedicated `string` type property which for this scenario is called `ClsAsString`. 

Here's how the two properties are configured in the TagHelpers:

```csharp
public Ext.Net.Union<string, string[]> Cls
{
    get => Model.Cls;
    set => Model.Cls = value;
}

[HtmlAttributeName("clsAsString")]
public string ClsAsString
{
    get => Model.Cls.As<string>();
    set => Model.Cls = value;
}
```

If configuring within a TagHelper, there are several options for setting a string value:

```html
// Use ClsAsString property
<ext-panel clsAsString="test" />

// Explicit string declaration
<ext-panel cls=@("test") />

// Wrap in single quotes
<ext-panel cls='"test"' />
```
