### ISSUE TITLE
absent：ext-abstractcomponent`s ContextMenuID string property

### ISSUE THREAD

**Issue by zgcgwin** [extnet/Ext.NET#1767]

**Comment by fabriciomurta** [comment]
Confirmed, yet this config is not in Ext JS's original API (that's why it currently is absent). As we don't have an issue specific to this aspect, I will point here examples in Examples Explorers using this (nice indeed) feature:

#### WebForms examples matching `ContextMenuID`

1. [Miscellaneous > Bin_HtmlBin > Overview](https://examples5.ext.net/#/Miscellaneous/Bin_HtmlBin/Overview/)
2. [Toolbar > Menu > Context_Menu](https://examples5.ext.net/#/Toolbar/Menu/Context_Menu/)
3. [Toolbar > Menu > Controls_In_Menu](https://examples5.ext.net/#/Toolbar/Menu/Controls_In_Menu/)

No example in MVC Examples explorer for Ext.NET 5 highlights this feature.
