### ISSUE TITLE
GridFilters activate and deactivate events are fired inconsistently

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#321]
http://forums.ext.net/showthread.php?26003
http://www.sencha.com/forum/showthread.php?269741

Fixed in trunk, revision 5330. Review after Sencha fix.
An additional fix for ListFilter, revision 5332. Review after Sencha fix.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.2 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.3 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
The issue has been reproduced in Ext.NET 4.x. But that's not an issue at all, the activate/deactivate events are no longer part of the GridFilters in 4.x, which no longer is a grid panel's feature, but now a plugin.

After checking the [documentation on the String Filter on Ext JS 6.5.3](http://docs.sencha.com/extjs/6.5.3/classic/Ext.grid.filters.filter.String.html), the following can be understood:
- the absence of events becomes clear
- there's still an 'active' property and setter methods to handle its active state
- the documentation on setActive() states it sets the state and triggers the corresponding events (not clear)
- setting the grid [store's FilterChange event](http://docs.sencha.com/extjs/6.5.3/classic/Ext.data.Store.html#event-filterchange), it gets triggered on filter changes, so that's the event expected to be triggered.

This indicates the feature now no longer should have the activate and deactivate events from Ext.NET and thei must be removed from the code, as not being functional for some time, either by Ext.NET 3.0 or 4.0 releases.

The correct event to use is the grid store's 'filterchange' event.

**Comment by fabriciomurta** [comment]
Issue #1594 tracks the defect, for removing the misleading exported events from Ext.NET.
