### ISSUE TITLE
Toolbar in north region shines through south region

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#371]
http://forums.ext.net/showthread.php?27121
http://www.sencha.com/forum/showthread.php?275502

**Update:** Issue still open after 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.2 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.3 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
Sencha claims this issue has been fixed for a while now. So there's not much point on keeping this open. Besides, the original Ext.NET forum thread that lead to this was not aimed at this issue, and it is not clear how exactly to reproduce the issue here, so we're considering Sencha position. If we are wrong and you still reproduce the problem with toolbar and border layout's regions, kindly let us know.
