### ISSUE TITLE
404 error loading MVC examples Draw/Basic: [Analytics, Pie Chart and Punch Chart]

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#709]
The three MVC examples below in Draw/Basic are unable to load due to 404 error to required resources:
- Analytics
- Pie Chart
- Punch Chart

There is an attempt to load an (seemingly unnecessary?) WebResource.axd?<...> that is absent and results on an error window during load.

The expected screen is not shown afterwards and the example is unusable.
This error has been reported on #673 item 8.

**Comment by fabriciomurta** [comment]
`Ext.Net.ResourceManager` is losing its `RenderStyles` property during `Ext.Net.DrawContainer` resources collecting when `Ext.Net.BaseControl.GetThemes()` is called. Outer event is `Ext.Net.BaseControl.PreRenderAction()`.
Path:
- `Ext.Net.BaseControl`
- `Ext.Net.Observable`
- `Ext.Net.AbstractContainer`; `Render` method
- During page loading.

**Comment by fabriciomurta** [comment]
The controller has no access to the ResourceManager defined on the view.
Then, in `Ext.Net.ConfigScriptBuilder.Build(LazyMode, bool)`, a new, blank and default resourceManager is defined.

This resourceManager has `renderStyles=None`, so the resulting link on `DrawComponent` does not point to the embedded resource, making the page fail.

**Comment by fabriciomurta** [comment]
Talking to @geoffreymcgill, we confirmed the problem on that part, and related to the removal of files from the embedded file list on Ext.NET.
Probably the best approach to address this issue, at least temporarily, would be to do the following suggested change on ConfigScriptBuilder.cs:~104:
`SelfRenderingPage pageHolder = new SelfRenderingPage();`
`ResourceManager newMgr = new ResourceManager(true);`
`newMgr.RenderScripts = ResourceLocationType.None; // <-- switch to .Embedded?`
`newMgr.RenderStyles = ResourceLocationType.None; // <-- switch to .Embedded?`
`newMgr.IDMode = IDMode.Explicit;`
`newMgr.IsDynamic = true;`

For the possible side effects, I will ask feedback also from @DaniilVeriga  and @vladsch.

**Comment by DaniilVeriga** [comment]
Thank you for all the investigation, it helped a lot!

Fixed in the revision #6347. It goes to 3.1.0.

A small summary:

1. The problem was there before removing files from the embedded list, but it didn't appear because sencha-charts-all.css file was embedded (but it should not).
2. Switching to .Embedded  is not an option, because .None is there for a reason - it guarantees that no resources are registered during creating of a component's config.
3. Ideally, RenderStyles (and other ResourceManager's setting) should not be used in a DrawContainer's Resources property, But it is a specific component and requires some custom logic in the Resources property and we don't have a good mechanism to avoid it.
4. It was quite difficult to come up with a fix without a need to do a lot of changes and be sure that it doesn't break some other scenario (testing all possible scenarios might take forever:)).

**Comment by DaniilVeriga** [comment]
This forum thread caused us to know that the problem was not fixed in a case with dynamic partial view rendering.
http://forums.ext.net/showthread.php?54511

Also a more wider problem has been discovered - PartialViewResult didn't read global settings (like RenderStyles, RenderScripts, RTL, Theme, ScriptMode) that are essential for registering of resources.

Both the issues are fixed in the revision 6364 (trunk). It goes to 3.1.0.
