### ISSUE TITLE
Viewport fails if AutoScroll is true and Ext.supports.Touch is true

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#928]
http://forums.ext.net/showthread.php?60262
https://www.sencha.com/forum/showthread.php?297197

The issue might be easily tested with this hack regardless you are on a touch screen or not.

```
Ext.feature.detect = function () {
    Ext.supports.Touch = true;
}
```

**UPDATE:** It has been fixed. Review after the next ExtJS upgrade - 5.1.2 or later.
**UPDATE:** in ExtJS 6.0.1, the thread is still open requesting more information.

**Comment by fabriciomurta** [comment]
I don't see an `autoScroll` setting [on Sencha docs](http://docs.sencha.com/extjs/6.0/6.0.2-classic/#!/api/Ext.container.Viewport) thus couldn't reproduce the issue in the fiddle below. Is there a chance this issue is Ext.NET-specific?
[Scrollable viewport's body on afterLayout](https://fiddle.sencha.com/#fiddle/196g)

If I remove the override created to fix this (extnet/Premium@8a5b8a), I can still reproduce the issue on Ext.NET. The error is triggered from an existing override of `Ext.plugin.ViewPort` (the line doing `document.body.scrollTop = 0`). So, another suspicion the issue is due to other overrides.

**Comment by fabriciomurta** [comment]
This issue is not reproducible in Ext.NET 4 after ExtJS 6.2.0 upgrade.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Sencha requires more information to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Sencha requires more information to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.3 release. Sencha requires more information to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Sencha requires more information to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Sencha requires more information to reproduce the issue.
