### ISSUE TITLE
ComboBox's ForceSelection="true" doesn't allow to clear the selected item

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#932]
http://forums.ext.net/showthread.php?60272

**Skipped test against Ext.NET 4:** The pointed example in examples explorer is not running at all after scripts' updates.

**Update:** Discussion in sencha: [How To Re-Empty ComboBox when forceSelection is Set To TRUE ](https://www.sencha.com/forum/showthread.php?182119)
Workaround: use an empty/dummy entry to work as the clear item.

**Update:** This is not reproducible in 6.0.1 -- FIXED on [EXTJS-18465, for 5.1.2](http://docs.sencha.com/extjs/5.1/whats_new/release_notes.html).

**Comment by fabriciomurta** [comment]
Fixed since ExtJS 5.1.2, no point in keeping it open, I guess! This fiddle [](https://fiddle.sencha.com/#fiddle/ibf) proves it is no longer reproducible.

In the fiddle:
1. switch to ExtJS 6.0.2 and re-run
2. select an entry on the combo box
3. delete the test and click somewhere outside the combobox to make it lose focus
The last chosen value gets selected in the combo box.

4. change the fiddle to have `allowBlank: false` in the combo box (it is originally with true!)
5. repeat steps 2 and 3
The combo box is left blank after it loses focus.
